--code generated by code lens feature (`generate model` feature above src_general.yml tables definitions)

with 

source as (

    select * from {{ source('property_management', 'properties') }}

),

renamed as (

    select
        id,
        created_at,
        name,
        address,
        city,
        state,
        zip_code,
        type,
        year_built,
        uploaded_at

    from source

)

select * from renamed
